In [2]:
%load_ext autoreload
%autoreload 2

In [8]:
from osrs_prices.client import Client

In [14]:
client = Client(user_agent="python api client - mattmflowers28@gmail.com")

                                             examine  ...                   name
0  Fabulously ancient mage protection enchanted i...  ...         3rd age amulet
1  A beautifully crafted axe, shaped by ancient s...  ...            3rd age axe
2  A beautifully crafted bow carved by ancient ar...  ...            3rd age bow
3        A beautiful cloak woven by ancient tailors.  ...          3rd age cloak
4  A fabulously ancient vine cloak as worn by the...  ...  3rd age druidic cloak

[5 rows x 9 columns]

In [18]:
client.get_latest(as_pandas=True).head()

   id      high      highTime       low       lowTime
0   2     189.0  1.732659e+09     185.0  1.732659e+09
1   6  192870.0  1.732659e+09  192870.0  1.732659e+09
2   8  187898.0  1.732659e+09  183895.0  1.732659e+09
3  10  183000.0  1.732659e+09  182702.0  1.732659e+09
4  12  204869.0  1.732659e+09  193275.0  1.732659e+09